;
; Measurement Values map extensions
;
$$measurement-values-map-extension //= (
  &(comid.spdm-indirect: 12) => spdm-indirect-map
)
spdm-indirect-map = {
  &(spdm.index: 0) => [ + uint ]
  * $$spdm-indirect-map-extension
}

;
; Flags map extensions
;
$$flags-map-extension //= (
  &(runtime-meas: 6) => bool
  &(immutable-meas: 7) => bool
  &(tcb-meas: 8) => bool
)
