
; CoMID triples-map-extension code points
comid.dependency-triples = 4
comid.domain-membership-triples = 5
comid.coswid-triples = 6

; CoMID measurement-values-map-extension code points
comid.spdm-indirect = 12

; CoMID flags-map-extension code points
comid.operational-flag-runtime-meas = 6
comid.operational-flag-immutable-meas = 7
comid.operational-flag-tcb-meas = 8

; SPDM spdm indirect code points
spdm.index = 0
spdm.measurement-type = 1
spdm.measurement-data = 2
spdm.measurement-digest = 3