;
; Measurement Values map extensions
;
$$measurement-values-map-extension //= (
  ? comid.spdm-indirect => [ + index-type]
)
index-type = uint

;
; Triples map extensions
;
; COSWID-TRIPLE-RECORD
;     The target environment $TE is capable of being loaded with software as identified by 
;     one or more COSWID tag identifiers $TagID.
$$triples-map-extension //= ( 
  ? comid.coswid-triples => [ + coswid-triple-record ]
)
coswid-triple-record = [ environment-map, [ + concise-swid-tag-id ] ]

; DOMAIN-DEPENDENCY-TRIPLE-RECORD
;     Predicate: $TD Target domain trust depends on $SD source domain(s)
$$triples-map-extension //= ( 
? comid.dependency-triples => [ + domain-dependency-triple-record ]
)

domain-dependency-triple-record = [
 $domain-type-choice, [ + $domain-type-choice ]
]
$domain-type-choice /= uint ; local scope identifier
$domain-type-choice /= tstr ; local scope identifier
$domain-type-choice /= tagged-uuid-type ; global scope identifier

; DOMAIN-MEMBERSHIP-TRIPLE-RECORD
; Predicate: $TD Target domain has member environment(s) $EV
$$triples-map-extension //= ( 
? comid.domain-membership-triples => [ + domain-membership-triple-record ]
)

domain-membership-triple-record = [
 $domain-type-choice, [ + environment-map ]
]
