;
; Measurement Values map extensions
;
$$measurement-values-map-extension //= (
  &(spdm-indirect: 12) => spdm-indirect-map
)
spdm-indirect-map = {
  &(index: 0) => [ + uint ]
  * $$spdm-indirect-map-extension
}

;
; Flags map extensions
;
$$flags-map-extension //= (
  ? &(is-runtime-meas: 6) => bool
  ? &(is-immutable: 7) => bool
  ? &(is-tcb: 8) => bool
)
