spdm-toc = #6.570(toc-map)
toc-map = {
  &(spdm.tagged-evidence: 0) => [ + $tagged-evidence-type-choice],
  ? &(spdm.rim-locators: 1) =>  [ + corim-locator-map ] ;see corim schema
  * $$toc-map-extension
}

$tagged-evidence-type-choice /= #6.571(concise-evidence-map)
; additional forms of evidence added here
