name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install tools
      run: gem install --user-install cbor-diag cddl
    - name: set up PATH
      run: echo "$(gem env gempath | cut -d':' -f1)/bin" >> $GITHUB_PATH
    - name: assemble and test
      run: make check
